/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CustomsRouteImport } from './routes/customs'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CustomsIndexRouteImport } from './routes/customs.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as CustomsVerifyRouteImport } from './routes/customs.verify'
import { Route as CustomsClearedRouteImport } from './routes/customs.cleared'
import { Route as AdminShipmentsRouteImport } from './routes/admin.shipments'
import { Route as AdminFleetRouteImport } from './routes/admin.fleet'

const CustomsRoute = CustomsRouteImport.update({
  id: '/customs',
  path: '/customs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomsIndexRoute = CustomsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CustomsRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const CustomsVerifyRoute = CustomsVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => CustomsRoute,
} as any)
const CustomsClearedRoute = CustomsClearedRouteImport.update({
  id: '/cleared',
  path: '/cleared',
  getParentRoute: () => CustomsRoute,
} as any)
const AdminShipmentsRoute = AdminShipmentsRouteImport.update({
  id: '/shipments',
  path: '/shipments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFleetRoute = AdminFleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/customs': typeof CustomsRouteWithChildren
  '/admin/fleet': typeof AdminFleetRoute
  '/admin/shipments': typeof AdminShipmentsRoute
  '/customs/cleared': typeof CustomsClearedRoute
  '/customs/verify': typeof CustomsVerifyRoute
  '/admin/': typeof AdminIndexRoute
  '/customs/': typeof CustomsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/fleet': typeof AdminFleetRoute
  '/admin/shipments': typeof AdminShipmentsRoute
  '/customs/cleared': typeof CustomsClearedRoute
  '/customs/verify': typeof CustomsVerifyRoute
  '/admin': typeof AdminIndexRoute
  '/customs': typeof CustomsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/customs': typeof CustomsRouteWithChildren
  '/admin/fleet': typeof AdminFleetRoute
  '/admin/shipments': typeof AdminShipmentsRoute
  '/customs/cleared': typeof CustomsClearedRoute
  '/customs/verify': typeof CustomsVerifyRoute
  '/admin/': typeof AdminIndexRoute
  '/customs/': typeof CustomsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/customs'
    | '/admin/fleet'
    | '/admin/shipments'
    | '/customs/cleared'
    | '/customs/verify'
    | '/admin/'
    | '/customs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/fleet'
    | '/admin/shipments'
    | '/customs/cleared'
    | '/customs/verify'
    | '/admin'
    | '/customs'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/customs'
    | '/admin/fleet'
    | '/admin/shipments'
    | '/customs/cleared'
    | '/customs/verify'
    | '/admin/'
    | '/customs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CustomsRoute: typeof CustomsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/customs': {
      id: '/customs'
      path: '/customs'
      fullPath: '/customs'
      preLoaderRoute: typeof CustomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customs/': {
      id: '/customs/'
      path: '/'
      fullPath: '/customs/'
      preLoaderRoute: typeof CustomsIndexRouteImport
      parentRoute: typeof CustomsRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/customs/verify': {
      id: '/customs/verify'
      path: '/verify'
      fullPath: '/customs/verify'
      preLoaderRoute: typeof CustomsVerifyRouteImport
      parentRoute: typeof CustomsRoute
    }
    '/customs/cleared': {
      id: '/customs/cleared'
      path: '/cleared'
      fullPath: '/customs/cleared'
      preLoaderRoute: typeof CustomsClearedRouteImport
      parentRoute: typeof CustomsRoute
    }
    '/admin/shipments': {
      id: '/admin/shipments'
      path: '/shipments'
      fullPath: '/admin/shipments'
      preLoaderRoute: typeof AdminShipmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fleet': {
      id: '/admin/fleet'
      path: '/fleet'
      fullPath: '/admin/fleet'
      preLoaderRoute: typeof AdminFleetRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminFleetRoute: typeof AdminFleetRoute
  AdminShipmentsRoute: typeof AdminShipmentsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminFleetRoute: AdminFleetRoute,
  AdminShipmentsRoute: AdminShipmentsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CustomsRouteChildren {
  CustomsClearedRoute: typeof CustomsClearedRoute
  CustomsVerifyRoute: typeof CustomsVerifyRoute
  CustomsIndexRoute: typeof CustomsIndexRoute
}

const CustomsRouteChildren: CustomsRouteChildren = {
  CustomsClearedRoute: CustomsClearedRoute,
  CustomsVerifyRoute: CustomsVerifyRoute,
  CustomsIndexRoute: CustomsIndexRoute,
}

const CustomsRouteWithChildren =
  CustomsRoute._addFileChildren(CustomsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CustomsRoute: CustomsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
